export const compatibilityReasonCodes = {
    OUTCOME_SCHEMA_MISMATCH: "OUTCOME_SCHEMA_MISMATCH",
    RESOLUTION_SOURCE_MISMATCH: "RESOLUTION_SOURCE_MISMATCH",
    SETTLEMENT_LAG_HIGH: "SETTLEMENT_LAG_HIGH",
    TIME_BOUNDARY_AMBIGUOUS: "TIME_BOUNDARY_AMBIGUOUS",
    RULE_TEXT_CONFLICT: "RULE_TEXT_CONFLICT",
    LOW_METADATA_CONFIDENCE: "LOW_METADATA_CONFIDENCE",
    FEE_MODEL_MISMATCH: "FEE_MODEL_MISMATCH",
    STRUCTURAL_MARKET_MISMATCH: "STRUCTURAL_MARKET_MISMATCH",
    PROPOSITION_SIMILARITY_LOW: "PROPOSITION_SIMILARITY_LOW",
    RESOLUTION_AUTHORITY_CONFLICT: "RESOLUTION_AUTHORITY_CONFLICT",
    SETTLEMENT_TYPE_MISMATCH: "SETTLEMENT_TYPE_MISMATCH",
    CONSERVATIVE_SETTLEMENT_ANCHOR_REQUIRED: "CONSERVATIVE_SETTLEMENT_ANCHOR_REQUIRED"
} as const;

export type CompatibilityReasonCode =
    typeof compatibilityReasonCodes[keyof typeof compatibilityReasonCodes];
