export const geopoliticalTrumpAcquireGreenland20261231TriLaneId =
  "POLITICS_GEOPOLITICAL_TRUMP_ACQUIRE_GREENLAND_2026_12_31_TRI_LIMITLESS_OPINION_POLYMARKET_PREDICT" as const;

export const geopoliticalTrumpAcquireGreenland20261231LimitlessPolymarketPairLaneId =
  "POLITICS_GEOPOLITICAL_TRUMP_ACQUIRE_GREENLAND_2026_12_31_PAIR_LIMITLESS_POLYMARKET" as const;

export const geopoliticalTrumpAcquireGreenland20261231LimitlessOpinionPairLaneId =
  "POLITICS_GEOPOLITICAL_TRUMP_ACQUIRE_GREENLAND_2026_12_31_PAIR_LIMITLESS_OPINION" as const;

export const geopoliticalTrumpAcquireGreenland20261231LimitlessPredictPairLaneId =
  "POLITICS_GEOPOLITICAL_TRUMP_ACQUIRE_GREENLAND_2026_12_31_PAIR_LIMITLESS_PREDICT" as const;

export const geopoliticalTrumpAcquireGreenland20261231OpinionPolymarketPairLaneId =
  "POLITICS_GEOPOLITICAL_TRUMP_ACQUIRE_GREENLAND_2026_12_31_PAIR_OPINION_POLYMARKET" as const;

export const geopoliticalTrumpAcquireGreenland20261231OpinionPredictPairLaneId =
  "POLITICS_GEOPOLITICAL_TRUMP_ACQUIRE_GREENLAND_2026_12_31_PAIR_OPINION_PREDICT" as const;

export const geopoliticalTrumpAcquireGreenland20261231PolymarketPredictPairLaneId =
  "POLITICS_GEOPOLITICAL_TRUMP_ACQUIRE_GREENLAND_2026_12_31_PAIR_POLYMARKET_PREDICT" as const;

export const politicsGeopoliticalTrumpAcquireGreenland20261231LaneIds = [
  geopoliticalTrumpAcquireGreenland20261231TriLaneId,
  geopoliticalTrumpAcquireGreenland20261231LimitlessPolymarketPairLaneId,
  geopoliticalTrumpAcquireGreenland20261231LimitlessOpinionPairLaneId,
  geopoliticalTrumpAcquireGreenland20261231LimitlessPredictPairLaneId,
  geopoliticalTrumpAcquireGreenland20261231OpinionPolymarketPairLaneId,
  geopoliticalTrumpAcquireGreenland20261231OpinionPredictPairLaneId,
  geopoliticalTrumpAcquireGreenland20261231PolymarketPredictPairLaneId
] as const;

export type PoliticsGeopoliticalTrumpAcquireGreenland20261231LaneId =
  typeof politicsGeopoliticalTrumpAcquireGreenland20261231LaneIds[number];
